### ISSUE TITLE
Move boilerplate files out of '2.1' folder and start using GitHub Releases

### ISSUE THREAD

**Issue by j0rdsta** [OutfitDelivery/boilerplate#2]
Yo yoooo! Having this '2.1' folder inside the root of this Git repository makes it a bit tricky to download the boilerplate and work directly from it - if I were to download a ZIP of this repo and attempt to directly upload it straight to Outfit, it'll fail because it needs the index.html.mst in the root of the ZIP.

Can we move everything out from inside this folder? It'll make it much easier for Delivery members to use this repo directly.

We should also look into using GitHub's Releases feature so that when we bump the version number of the boilerplate, we get a handy dandy ZIP that's set in stone: https://docs.github.com/en/free-pro-team@latest/github/administering-a-repository/managing-releases-in-a-repository

**Comment by mmagin1** [comment]
Yeah can look into that 👍. The reason for setting it in this way originally to directly parry the S3 servers copy of the JS files.

**Comment by mmagin1** [comment]
Updated file structure and moved to Github releases.
